//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashoundCoachTravels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coaches
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Seats { get; set; }
        public string DateAdded { get; set; }
        public string VehicleNumber { get; set; }
    
        public virtual Trips Trips { get; set; }
    }
}
