//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashoundCoachTravels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int Id { get; set; }
        public string DateBooked { get; set; }
        public string NumPeople { get; set; }
        public string Status { get; set; }
        public string DatePayedAdvance { get; set; }
        public string DatePayedFull { get; set; }
        public string Advance { get; set; }
    
        public virtual Trips Trip { get; set; }
        public virtual AspNetUser AspNetUsers { get; set; }
    }
}
