// <auto-generated />
namespace DashoundCoachTravels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Table_Locations_newentries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_Locations_newentries));
        
        string IMigrationMetadata.Id
        {
            get { return "201811201326294_Table_Locations_newentries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
